### ISSUE TITLE
Duplicate namespace in shortcode.php

### ISSUE THREAD

**Issue by JeffCleverley** [KnowTheCode/php-output-buffer-lab#1]
Hey Tonya

There are duplicate namespaces in `php-output-buffer-lab/src/shortcode.php`

Jeff

**Comment by hellofromtonya** [comment]
Thank you, @JeffCleverley, for bringing it to my attention.  The issue has been resolved per [commit 5ccd154](https://github.com/KnowTheCode/php-output-buffer-lab/commit/5ccd15497d015c1e5ad9deea5433f197c0dfadcc).
